image: mcr.microsoft.com/dotnet/core/sdk:3.1

stages:
    - build
    
before_script:
  - "dotnet restore"
    
build-dev:
    stage: build
    only:
        - develop
    script:
        - "dotnet build"
        
build-master:
    stage: build
    only:
        - master
    script:
        - "dotnet build"
