version: '3.8'

services:
    sql:
        image: mcr.microsoft.com/mssql/server:2017-latest
        restart: always
        environment:
            - ACCEPT_EULA=Y
            - SA_PASSWORD=Admin1234!
        ports:
            - "4000:1433"